ElastiCache Redis
dxw/terraform-dxw-dalmatian-infrastructure pull request #67
Opened 2024-03-21 11:44 UTC by Stretch96

* Conditionally launch ElastiCache Redis
* Allows chosing either Cluster or Serverless
* ElastiCache also supports Memcache, but this module currently only supports Redis

2024-03-21 14:44 UTC, rjw1 requested changes

2024-03-21 14:44 UTC, rjw1 commented on variables.tf
> +    Map of RDSs (The key will be the rds name). Values in here will override `infrastructure_rds_defaults` values if set."
its not RDS.

2024-03-21 15:41 UTC, Stretch96 commented on variables.tf
> +    Map of RDSs (The key will be the rds name). Values in here will override `infrastructure_rds_defaults` values if set."
Ah ... Updated 👍 ...

2024-03-21 16:23 UTC, rjw1 requested changes

2024-03-21 16:23 UTC, rjw1 commented on variables.tf
> +      rds-name = {
this line to :)

2024-03-22 10:34 UTC, Stretch96 commented on variables.tf
> +      rds-name = {
Updated 👍

2024-03-22 10:51 UTC, rjw1 approved these changes
looks fine

2024-03-22 16:08 UTC, merged